-- Problem 2

-- Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
-- 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
-- By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


   
fib 0 = 0
fib 1 = 1
fib n = fib (n-1) + fib (n-2)

fib4millionSumt = sum [ fib x | x <- [0..4000000], even (fib x)]

main =
    print fib4millionSumt 
